# send config file, both for filewatcher & rest
[filewatcher]
dirsif = "./inbound/sif"
dirxapi = "./inbound/xapi"

[grpc]
namespace = "Aa5fKf2UmyfCufY6JFmQpX12j1jjDFSUfbFUEE92t2nx"
ctxsif = "abc-sif"
ctxxapi = "abc-xapi"
server = "192.168.76.10"
port = 5777